global:
  resolve_timeout: 5m
route:
  receiver: webhook_receiver
receivers:
    - name: webhook_receiver
      webhook_configs:
        - url: 'https://webhook-test.com/737b55bf10e2e3ed613733e8d85b207a'
          send_resolved: false