global:
  resolve_timeout: 5m
route:
  receiver: webhook_receiver
receivers:
    - name: webhook_receiver
      webhook_configs:
      # Utilize: https://webhook.site/
        - url: 'https://webhook.site/f7dc6a60-455e-4ef2-a47f-2e4ad85ebf3e'
          send_resolved: false
