version: '3.8'
  
services:

  prometheus:
    image: prom/prometheus:v2.49.1
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/rules.yml:/etc/prometheus/rules.yml
    ports:
      - 80:9090
    restart: unless-stopped
    networks:
       monitoring:

  node-exporter:
    image: prom/node-exporter:v1.7.0
    ports:
      - 9100:9100
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
      - '--collector.systemd'
      - '--collector.processes'
    restart: unless-stopped 
    networks:
       monitoring:

  prometheus-msteams:
    image: quay.io/prometheusmsteams/prometheus-msteams:v1.5.2
    ports:
      - 2000:2000
    environment:
      - TEAMS_INCOMING_WEBHOOK_URL="https://outlook.office.com/webhook/xxx"
      - TEAMS_REQUEST_URI=alertmanager
    restart: unless-stopped
    networks:
       monitoring:

  alertmanager:
    image: prom/alertmanager:v0.26.0
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/config.yml:/etc/alertmanager/config.yml
    command:
      - '--config.file=/etc/alertmanager/config.yml'
    restart: unless-stopped
    networks:
       monitoring:

  grafana:
    image: grafana/grafana:10.3.1
    ports:
      - 3000:3000

    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    networks:
       monitoring:

networks:
  monitoring:
     name: monitoring

volumes:
    prometheus_data: {}
    grafana_data: {}
